config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "/signup", to: "users#new"
  get "/auth/:provider/callback", to: "users#twitter_login"
  get "/admin/users", to: "users#index"
  patch "/users/:id/profile", to: "users#update_profile", as: "update_profile"
  patch "/users/:id/password", to: "users#update_password", as: "update_password"
  patch "/users/:id/avatar", to: "users#update_avatar", as: "update_avatar" # デモアカウント用
  get "/users/:id/delete", to: "users#delete", as: "delete_page"
  resources :users, except: [:index, :update]

  resources :account_activations, only: [:new, :create, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :habits, only: [:destroy]
  get "/habits/select", to: "habits#select"

  get "/makes/title", to: "makes#title"
  get "/makes/norm_description", to: "makes#norm_description"
  get "/makes/norm_input", to: "makes#norm_input"
  get "/makes/rule1_description", to: "makes#rule1_description"
  get "/makes/rule1_input", to: "makes#rule1_input"
  get "/makes/situation_description", to: "makes#situation_description"
  get "/makes/situation_input", to: "makes#situation_input"
  get "/makes/rule2_description", to: "makes#rule2_description"
  get "/makes/rule2_input", to: "makes#rule2_input"
  resources :makes, only: [:create, :show, :update]

  get "/quits/title", to: "quits#title"
  get "/quits/situation_description", to: "quits#situation_description"
  get "/quits/situation_input", to: "quits#situation_input"
  get "/quits/rule1_description", to: "quits#rule1_description"
  get "/quits/rule1_input", to: "quits#rule1_input"
  get "/quits/rule2_description", to: "quits#rule2_description"
  get "/quits/rule2_input", to: "quits#rule2_input"
  resources :quits, only: [:create, :show, :update]
end

app/models/quit.rb
class Quit < Habit
  validate :check_number_of_quits

  private

    def check_number_of_quits
      if user && user.quits.count >= 50
        errors.add(:base, "同時に作成できるルールは50個までです")
      end
    end
end

app/controllers/quits_controller.rb
class QuitsController < HabitsController
  before_action :check_login
  before_action :forbid_direct_access, except: [:title, :show]
  before_action :check_number_of_quits, only: [:title]
  before_action :set_title, only: [:situation_description, :situation_input, :rule1_description, :rule1_input, :rule2_description, :rule2_input]
  before_action :set_rule1, only: [:rule2_description, :rule2_input]
  before_action :check_correct_user, only: [:show]

  def title
  end

  def situation_description
  end

  def situation_input
  end

  def rule1_description
    @situation = params[:quit][:situation]
  end

  def rule1_input
    @situation = params[:quit][:situation]
  end

  def rule2_description
  end

  def rule2_input
  end

  def create
    quit = current_user.quits.build(quit_params)
    if quit.save
      flash[:success] = "自分ルールを作成しました！"
      redirect_to quit
    else
      flash[:warning] = "データの保存に失敗しました。お手数ですがもう一度やり直してください。"
      redirect_to quits_title_url
    end
  end

  def update
    quit = current_user.quits.find(params[:id])
    quit.update!(quit_params)
    head :no_content
  end

  def show
    @quit = current_user.quits.find(params[:id])
  end

  private

    def quit_params
      params.require(:quit).permit(:title, :rule1, :rule2, :progress)
    end

    def forbid_direct_access
      redirect_to quits_title_path if request.referer.nil?
    end

    def check_number_of_quits
      if current_user.quits.count >= 50
        flash[:warning] = "同時に作成できるルールは50個ずつまでです"
        redirect_to current_user
      end
    end

    def set_title
      @title = params[:quit][:title]
    end

    def set_rule1
      @rule1 = params[:quit][:rule1]
    end
end

app/helpers/quits_helper.rb
module QuitsHelper
end

app/views/quits/new1.html.haml
.container.quits-new-wrapper
  = render "shared/stepbar", step: 1, type: "quit"
  .jumbotron.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      質問に答えながら２つの自分ルールを作成していきます。
      %br
      やめたい習慣はなんですか？

    = form_for(:quit, url: quits_new_2_path, method: :get) do |f|
      = f.text_field :title, required: true, maxlength: 255, class: "form-control mt-5 placeholder", placeholder: "ex）ついYouTubeを見てしまう"

      = f.submit "次へ", class: "btn btn-info mt-5"

app/views/quits/new2.html.haml
.container.makes-new-wrapper
  .jumbotron.mt-5.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      その習慣をついやってしまうのはどのような状況ですか？
      %br
      すぐに思いつかなかったら数日生活してみて、やってしまう状況を記録してみましょう

    = form_for(:quit, url: quits_new_3_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.submit "次へ", class: "btn btn-info mt-5"

app/views/quits/new4.html.haml
.container.makes-new-wrapper
  .jumbotron.mt-5.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      やめたい習慣を代わりの行動におきかえて１つ目の自分ルールを作ります。
      %br
      「やってしまう状況になったら代わりの行動をする」という形で作ってみましょう。
      %br
      代わりの行動はやめたい習慣と同時にはできないものにしてください。

    = form_for(:quit, url: quits_new_5_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.hidden_field :situation, value: @situation
      = f.submit "次へ", class: "btn btn-info mt-5"

app/views/quits/new5.html.haml
.container.quits-new-wrapper.text-center
  = render "shared/stepbar", step: 3, type: "quit"
  .jumbotron
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      下のフォームを編集して１つ目の自分ルールを作成してください。
      %br
      ex）自分の部屋で暇になったら本を読む

    = form_for(:quit, url: quits_new_6_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.text_area :rule1, required: true, maxlength: 255, class: "form-control mt-5 placeholder", value: "#{@situation}",
                            placeholder: "「やってしまう状況になったら代わりの行動をする」という形で自分ルールを作成してください"

      = f.submit "次へ", class: "btn btn-info mt-5"

  %a.hint-text.d-inline-block.mt-3.mb-5{"data-toggle" => "modal", "href" => "#quitHintModal1"}
    ルール作成のヒント

  #quitHintModal1.modal.fade{"tab-index" => "-1", "role" => "dialog", "aria-labelledby" => "quitHintModal1Label", "aria-hidden" => "true"}
    .modal-dialog.modal-dialog-centered{"role" => "document"}
      .modal-content.text-justify
        .modal-header
          %h5.m-0.modal-titel#quitHintModal1Title ヒント
          %button.close{"type" => "button", "data-dismiss" => "modal", "aria-label" => "閉じる"}
            %span{"aria-hidden" => "true"} &times;
        .modal-body
          %p
            &emsp;１度はじめてしまった事を自分の意志の力でやめるのは非常に難しいです。なので、すでにある習慣をやめるためには「その行動をやりはじめないようにすること」が大切です。
          %p
            &emsp;そのために有効なのが「習慣を別の行動におきかえる」ことです。「普段だったらやめたい習慣をやってしまう状況になったら、代わりの行動をやる」というルールを作ることで意志の力に頼らずにやめることを目指します。
          %p
            ・タバコを吸ってしまう→ガムを噛む
            %br
            ・ジュースを飲んでしまう→お茶を飲む
            %br
            のように同時にはできない行動におきかえてみましょう。

app/views/quits/new6.html.haml
.container.makes-new-wrapper
  .jumbotron.mt-5.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      次にやめたい習慣を簡単にはできないようにするルールを決めましょう。
      %br
      コツは今より少なくとも２０秒以上余計に時間がかかるようにすることです。

    = form_for(:quit, url: quits_new_7_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.hidden_field :rule1, value: @rule1
      = f.submit "次へ", class: "btn btn-info mt-5"

app/views/quits/new7.html.haml
.container.quits-new-wrapper.text-center
  = render "shared/stepbar", step: 4, type: "quit"
  .jumbotron
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      ２つ目の自分ルールを作成してください。
      %br
      ex) スマホからアプリを消してYouTubeはパソコンで見るようにする

    = form_for(:quit, url: quits_path) do |f|
      = f.hidden_field :title, value: @title
      = f.hidden_field :rule1, value: @rule1
      = f.text_area :rule2, required: true, maxlength: 255, class: "form-control mt-5 placeholder",
                            placeholder: "やめたい習慣を簡単にはできないようにする自分ルールを作成してください"

      = f.submit "完成！", class: "btn btn-info mt-5"

  %a.hint-text.d-inline-block.mt-3.mb-5{"data-toggle" => "modal", "href" => "#quitHintModal2"}
    ルール作成のヒント

  #quitHintModal2.modal.fade{"tab-index" => "-1", "role" => "dialog", "aria-labelledby" => "quitHintModal2Label", "aria-hidden" => "true"}
    .modal-dialog.modal-dialog-centered{"role" => "document"}
      .modal-content.text-justify
        .modal-header
          %h5.m-0.modal-titel#quitHintModal2Title ヒント
          %button.close{"type" => "button", "data-dismiss" => "modal", "aria-label" => "閉じる"}
            %span{"aria-hidden" => "true"} &times;
        .modal-body
          %p
            &emsp;すでに習慣化されている行動はほとんどが簡単にはじめられるものではないでしょうか？もし間食をやめたいと思っていても、常に家にお菓子が置いてある状況で我慢するのは非常に難しいです。
          %p
            &emsp;やりたくても簡単にはじめられない状況を作ることで、その欲求をやり過ごし、面倒さが上回るような仕組みを作ります。
          %p
            ・間食してしまう→ストックをやめて毎回コンビニに買いにいく
            %br
            ・ネットで衝動買いしてしまう→支払い情報や住所を毎回自分で入力する

app/views/quits/rule1_description.html.haml
.container.quits-new-wrapper
  .jumbotron.mt-5.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      やめたい習慣を代わりの行動におきかえて１つ目の自分ルールを作ります。
      %br
      「やってしまう状況になったら代わりの行動をする」という形で作ってみましょう。
      %br
      代わりの行動はやめたい習慣と同時にはできないものにしてください。

    = form_for(:quit, url: quits_rule1_input_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.hidden_field :situation, value: @situation
      = f.submit "次へ", class: "btn btn-info mt-5"

app/views/quits/rule1_input.html.haml
.container.quits-new-wrapper.text-center
  = render "shared/stepbar", step: 3, type: "quit"
  .jumbotron
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      下のフォームを編集して１つ目の自分ルールを作成してください。
      %br
      ex）自分の部屋で暇になったら本を読む

    = form_for(:quit, url: quits_rule2_description_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.text_area :rule1, required: true, maxlength: 255, class: "form-control mt-5 placeholder", value: "#{@situation}",
                            placeholder: "「やってしまう状況になったら代わりの行動をする」という形で自分ルールを作成してください"

      = f.submit "次へ", class: "btn btn-info mt-5"

  %a.hint-text.d-inline-block.mt-3.mb-5{"data-toggle" => "modal", "href" => "#quitHintModal1"}
    ルール作成のヒント

  #quitHintModal1.modal.fade{"tab-index" => "-1", "role" => "dialog", "aria-labelledby" => "quitHintModal1Label", "aria-hidden" => "true"}
    .modal-dialog.modal-dialog-centered{"role" => "document"}
      .modal-content.text-justify
        .modal-header
          %h5.m-0.modal-titel#quitHintModal1Title ヒント
          %button.close{"type" => "button", "data-dismiss" => "modal", "aria-label" => "閉じる"}
            %span{"aria-hidden" => "true"} &times;
        .modal-body
          %p
            &emsp;１度はじめてしまった事を自分の意志の力でやめるのは非常に難しいです。なので、すでにある習慣をやめるためには「その行動をやりはじめないようにすること」が大切です。
          %p
            &emsp;そのために有効なのが「習慣を別の行動におきかえる」ことです。「普段だったらやめたい習慣をやってしまう状況になったら、代わりの行動をやる」というルールを作ることで意志の力に頼らずにやめることを目指します。
          %p
            ・タバコを吸ってしまう→ガムを噛む
            %br
            ・ジュースを飲んでしまう→お茶を飲む
            %br
            のように同時にはできない行動におきかえてみましょう。

app/views/quits/rule2_description.html.haml
.container.quits-new-wrapper
  .jumbotron.mt-5.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      次にやめたい習慣を簡単にはできないようにするルールを決めましょう。
      %br
      コツは今より少なくとも２０秒以上余計に時間がかかるようにすることです。

    = form_for(:quit, url: quits_rule2_input_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.hidden_field :rule1, value: @rule1
      = f.submit "次へ", class: "btn btn-info mt-5"

app/views/quits/rule2_input.html.haml
.container.quits-new-wrapper.text-center
  = render "shared/stepbar", step: 4, type: "quit"
  .jumbotron
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      ２つ目の自分ルールを作成してください。
      %br
      ex) スマホからアプリを消してYouTubeはパソコンで見るようにする

    = form_for(:quit, url: quits_path) do |f|
      = f.hidden_field :title, value: @title
      = f.hidden_field :rule1, value: @rule1
      = f.text_area :rule2, required: true, maxlength: 255, class: "form-control mt-5 placeholder",
                            placeholder: "やめたい習慣を簡単にはできないようにする自分ルールを作成してください"

      = f.submit "完成！", class: "btn btn-info mt-5"

  %a.hint-text.d-inline-block.mt-3.mb-5{"data-toggle" => "modal", "href" => "#quitHintModal2"}
    ルール作成のヒント

  #quitHintModal2.modal.fade{"tab-index" => "-1", "role" => "dialog", "aria-labelledby" => "quitHintModal2Label", "aria-hidden" => "true"}
    .modal-dialog.modal-dialog-centered{"role" => "document"}
      .modal-content.text-justify
        .modal-header
          %h5.m-0.modal-titel#quitHintModal2Title ヒント
          %button.close{"type" => "button", "data-dismiss" => "modal", "aria-label" => "閉じる"}
            %span{"aria-hidden" => "true"} &times;
        .modal-body
          %p
            &emsp;すでに習慣化されている行動はほとんどが簡単にはじめられるものではないでしょうか？もし間食をやめたいと思っていても、常に家にお菓子が置いてある状況で我慢するのは非常に難しいです。
          %p
            &emsp;やりたくても簡単にはじめられない状況を作ることで、その欲求をやり過ごし、面倒さが上回るような仕組みを作ります。
          %p
            ・間食してしまう→ストックをやめて毎回コンビニに買いにいく
            %br
            ・ネットで衝動買いしてしまう→支払い情報や住所を毎回自分で入力する

app/views/quits/show.html.haml
.container.quits-show-wrapper.text-center
  .jumbotron.mt-5.mx-auto.p-0#quit-rule
    %section.title.border-bottom.px-3
      %p.section-title やめたい習慣
      %p.content
        = @quit.title
    %section.rule1.border-bottom.px-3
      %p.section-title ルール①
      %p.content
        = @quit.rule1
    %section.rule2.border-bottom.px-3
      %p.section-title ルール②
      %p.content
        = @quit.rule2
    %section.date.border-bottom.px-3
      %p.section-title 作成日
      %p.content
        = @quit.created_at.strftime('%Y/%m/%d')
    %section.px-3.d-none#quit-progress
      %p.section-title 進捗
      .progressRange
        = form_for(@quit, remote: true) do |f|
          = f.range_field :progress, min: 0, max: 100, step: 1, value: @quit.progress, onchange: 'Rails.fire(this.form, "submit")'
          %span
            = "#{@quit.progress}%"
  .row
    = link_to "画像をダウンロードする", "#", download: "myrule_#{@quit.id}", id: "quit-download", class: "btn btn-success col-6 offset-3 col-md-4 offset-md-4 mt-4 mb-2"
    = link_to "ルールを削除する", habit_path(@quit), method: :delete, class: "btn btn-secondary col-6 offset-3 col-md-4 offset-md-4 my-5", data: { confirm: "このルールを削除しますか？" }

app/views/quits/situation_description.html.haml
.container.quits-new-wrapper
  .jumbotron.mt-5.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      その習慣をついやってしまうのはどのような状況ですか？
      %br
      すぐに思いつかなかったら数日生活してみて、やってしまう状況を記録してみましょう

    = form_for(:quit, url: quits_situation_input_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.submit "次へ", class: "btn btn-info mt-5"

app/views/quits/situation_input.html.haml
.container.quits-new-wrapper
  = render "shared/stepbar", step: 2, type: "quit"
  .jumbotron.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      ついやってしまう状況を入力してください

    = form_for(:quit, url: quits_rule1_description_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.text_field :situation, required: true, maxlength: 150, class: "form-control mt-5 placeholder",
                                  placeholder: "ex）自分の部屋で暇になったとき"

      = f.submit "次へ", class: "btn btn-info mt-5"

app/views/quits/title.html.haml
.container.quits-new-wrapper
  = render "shared/stepbar", step: 1, type: "quit"
  .jumbotron.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      質問に答えながら２つの自分ルールを作成していきます。
      %br
      やめたい習慣はなんですか？

    = form_for(:quit, url: quits_situation_description_path, method: :get) do |f|
      = f.text_field :title, required: true, maxlength: 255, class: "form-control mt-5 placeholder", placeholder: "ex）ついYouTubeを見てしまう"

      = f.submit "次へ", class: "btn btn-info mt-5"