config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "/signup", to: "users#new"
  get "/auth/:provider/callback", to: "users#twitter_login"
  get "/admin/users", to: "users#index"
  patch "/users/:id/profile", to: "users#update_profile", as: "update_profile"
  patch "/users/:id/password", to: "users#update_password", as: "update_password"
  patch "/users/:id/avatar", to: "users#update_avatar", as: "update_avatar" # デモアカウント用
  get "/users/:id/delete", to: "users#delete", as: "delete_page"
  resources :users, except: [:index, :update]

  resources :account_activations, only: [:new, :create, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :habits, only: [:destroy]
  get "/habits/select", to: "habits#select"

  get "/makes/title", to: "makes#title"
  get "/makes/norm_description", to: "makes#norm_description"
  get "/makes/norm_input", to: "makes#norm_input"
  get "/makes/rule1_description", to: "makes#rule1_description"
  get "/makes/rule1_input", to: "makes#rule1_input"
  get "/makes/situation_description", to: "makes#situation_description"
  get "/makes/situation_input", to: "makes#situation_input"
  get "/makes/rule2_description", to: "makes#rule2_description"
  get "/makes/rule2_input", to: "makes#rule2_input"
  resources :makes, only: [:create, :show, :update]

  get "/quits/title", to: "quits#title"
  get "/quits/situation_description", to: "quits#situation_description"
  get "/quits/situation_input", to: "quits#situation_input"
  get "/quits/rule1_description", to: "quits#rule1_description"
  get "/quits/rule1_input", to: "quits#rule1_input"
  get "/quits/rule2_description", to: "quits#rule2_description"
  get "/quits/rule2_input", to: "quits#rule2_input"
  resources :quits, only: [:create, :show, :update]
end

app/models/make.rb
class Make < Habit
  validate :check_number_of_makes

  private

    def check_number_of_makes
      if user && user.makes.count >= 50
        errors.add(:base, "同時に作成できるルールは50個までです")
      end
    end
end

app/controllers/makes_controller.rb
class MakesController < HabitsController
  before_action :check_login
  before_action :forbid_direct_access, except: [:title, :show]
  before_action :check_number_of_makes, only: [:title]
  before_action :set_title, only: [:norm_description, :norm_input, :rule1_description, :rule1_input,
                                   :situation_description, :situation_input, :rule2_description, :rule2_input]
  before_action :set_rule1, only: [:situation_description, :situation_input, :rule2_description, :rule2_input]
  before_action :check_correct_user, only: [:show]

  def title
  end

  def norm_description
  end

  def norm_input
  end

  def rule1_description
    @norm = params[:make][:norm]
  end

  def rule1_input
    @norm = params[:make][:norm]
  end

  def situation_description
  end

  def situation_input
  end

  def rule2_description
    @situation = params[:make][:situation]
  end

  def rule2_input
    @situation = params[:make][:situation]
  end

  def create
    make = current_user.makes.build(make_params)
    if make.save
      flash[:success] = "自分ルールを作成しました！"
      redirect_to make
    else
      flash[:warning] = "データの保存に失敗しました。お手数ですがもう一度やり直してください。"
      redirect_to makes_title_url
    end
  end

  def update
    make = current_user.makes.find(params[:id])
    make.update!(make_params)
    head :no_content
  end

  def show
    @make = current_user.makes.find(params[:id])
  end

  private

    def make_params
      params.require(:make).permit(:title, :rule1, :rule2, :progress)
    end

    def forbid_direct_access
      redirect_to makes_title_path if request.referer.nil?
    end

    def check_number_of_makes
      if current_user.makes.count >= 50
        flash[:warning] = "同時に作成できるルールは50個ずつまでです"
        redirect_to current_user
      end
    end

    def set_title
      @title = params[:make][:title]
    end

    def set_rule1
      @rule1 = params[:make][:rule1]
    end
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/views/makes/new1.html.haml
.container.makes-new-wrapper
  = render "shared/stepbar", step: 1, type: "make"
  .jumbotron.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      質問に答えながら２つの自分ルールを作成していきます。
      %br
      身につけたい習慣はなんですか？

    = form_for(:make, url: makes_new_2_path, method: :get) do |f|
      = f.text_field :title, required: true, maxlength: 100, class: "form-control mt-5 placeholder", placeholder: "ex) 筋トレ"

      = f.submit "次へ", class: "btn btn-info mt-5"

app/views/makes/new2.html.haml
.container.makes-new-wrapper
  .jumbotron.mt-5.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      まずは１回の行動のノルマを決めます。
      %br
      最初はバカバカしいほど簡単なことから始めることがコツです。
      %br
      「やらないよりはやったほうがいい程度のこと」をノルマにしてみましょう。

    = form_for(:make, url: makes_new_3_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.submit "次へ", class: "btn btn-info mt-5"

app/views/makes/new4.html.haml
.container.makes-new-wrapper
  .jumbotron.mt-5.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      いま決めたノルマをすでにある習慣と結びつけて１つ目の自分ルールを作ります。
      %br
      「すでにある習慣を実行したら、ノルマを行う」という形で作ってみましょう。

    = form_for(:make, url: makes_new_5_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.hidden_field :norm, value: @norm
      = f.submit "次へ", class: "btn btn-info mt-5"

app/views/makes/new5.html.haml
.container.makes-new-wrapper.text-center
  = render "shared/stepbar", step: 3, type: "make"
  .jumbotron
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")

    %p.lead
      下のフォームを編集して１つ目の自分ルールを作成してください。
      %br
      ex) 夕飯を食べ終わったら１回スクワットをする

    = form_for(:make, url: makes_new_6_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.text_area :rule1, required: true, maxlength: 255, class: "form-control mt-5 placeholder", value: "#{@norm}",
                            placeholder: "「すでにある習慣を実行したらノルマを行う」という形で自分ルールを作成してください"

      = f.submit "次へ", class: "btn btn-info mt-5"
  %a.hint-text.d-inline-block.mt-3.mb-5{"data-toggle" => "modal", "href" => "#makeHintModal1"}
    ルール作成のヒント

  #makeHintModal1.modal.fade{"tab-index" => "-1", "role" => "dialog", "aria-labelledby" => "makeHintModal1Label", "aria-hidden" => "true"}
    .modal-dialog.modal-dialog-centered{"role" => "document"}
      .modal-content
        .modal-header
          %h5.m-0.modal-titel#makeHintModal1Title ヒント
          %button.close{"type" => "button", "data-dismiss" => "modal", "aria-label" => "閉じる"}
            %span{"aria-hidden" => "true"} &times;
        .modal-body.text-justify
          %p
            &emsp;自分の意志の力で習慣づくりをしようとすると挫折する確率が高くなってしまいます。
          %p
            &emsp;継続するコツは行動を「ルール化」してしまい、自分の意志とは関係なく実行することです。その方法の１つがすでにある習慣と新しくはじめたい行動をセットにするというものです。
          %p
            &emsp;「食事をする」「電車に乗る」「お風呂に入る」などの普段当たり前におこなっている行動にノルマを結びつけることで、気軽に有効なルールを決めることができます。
          %p
            &emsp;ノルマの頻度を調整したい場合は「月・水・金曜日は仕事が終わったらジムにいく」などの条件にしても大丈夫です。この時も必ずすでにある習慣とセットにしてください。

app/views/makes/new6.html.haml
.container.makes-new-wrapper
  .jumbotron.mt-5.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      ２つ目の自分ルールを作成していきます。
      %br
      ノルマを実行していく上で、うまくいかないことがあると思います。
      %br
      あらかじめその対策を考えておくことで、習慣づくりの成功率を上げましょう。

    = form_for(:make, url: makes_new_7_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.hidden_field :rule1, value: @rule1
      = f.submit "次へ", class: "btn btn-info mt-5"

app/views/makes/new8.html.haml
.container.makes-new-wrapper
  .jumbotron.mt-5.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      次に挫折しそうになった時の対策を考えましょう。
      %br
      どのような行動や考え方をすればその状況を克服できますか？
      %br
      「挫折しそうな状況になったら、対策を行う」という形で２つ目の自分ルールを作成してください。
    
    = form_for(:make, url: makes_new_9_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.hidden_field :rule1, value: @rule1
      = f.hidden_field :situation, value: @situation
      = f.submit "次へ", class: "btn btn-info mt-5"

app/views/makes/new9.html.haml
.container.makes-new-wrapper.text-center
  = render "shared/stepbar", step: 5, type: "make"
  .jumbotron
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      下のフォームを編集して２つ目の自分ルールを作成してください。
      %br
      ex) めんどくさいと思ったら太ってる自分の写真を見返す

    = form_for(:make, url: makes_path) do |f|
      = f.hidden_field :title, value: @title
      = f.hidden_field :rule1, value: @rule1
      = f.text_area :rule2, required: true, maxlength: 255, class: "form-control mt-5 placeholder", value: "#{@situation}",
                            placeholder: "「挫折しそうな状況になったら対策を行う」という形で自分ルールを作成してください"

      = f.submit "完成！", class: "btn btn-info mt-5"

  %a.hint-text.d-inline-block.mt-3.mb-5{"data-toggle" => "modal", "href" => "#makeHintModal2"}
    ルール作成のヒント

  #makeHintModal2.modal.fade{"tab-index" => "-1", "role" => "dialog", "aria-labelledby" => "makeHintModal2Label", "aria-hidden" => "true"}
    .modal-dialog.modal-dialog-centered{"role" => "document"}
      .modal-content
        .modal-header
          %h5.m-0.modal-titel#makeHintModal2Title ヒント
          %button.close{"type" => "button", "data-dismiss" => "modal", "aria-label" => "閉じる"}
            %span{"aria-hidden" => "true"} &times;
        .modal-body.text-justify
          %p
            &emsp;「どうしても時間がない」「どうしても疲れて眠い」というような状況では、無理にノルマをやるよりも代わりにやる日を決める方が有効です。
            %br
            ex) 「疲れて眠い場合は、寝てしまって次の日の朝起きたらすぐにノルマをやる。」

app/views/makes/norm_description.html.haml
.container.makes-new-wrapper
  .jumbotron.mt-5.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      まずは１回の行動のノルマを決めます。
      %br
      最初はバカバカしいほど簡単なことから始めることがコツです。
      %br
      「やらないよりはやったほうがいい程度のこと」をノルマにしてみましょう。

    = form_for(:make, url: makes_norm_input_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.submit "次へ", class: "btn btn-info mt-5"

app/views/makes/rule1_description.html.haml
.container.makes-new-wrapper
  .jumbotron.mt-5.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      いま決めたノルマをすでにある習慣と結びつけて１つ目の自分ルールを作ります。
      %br
      「すでにある習慣を実行したら、ノルマを行う」という形で作ってみましょう。

    = form_for(:make, url: makes_rule1_input_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.hidden_field :norm, value: @norm
      = f.submit "次へ", class: "btn btn-info mt-5"

app/views/makes/rule1_input.html.haml
.container.makes-new-wrapper.text-center
  = render "shared/stepbar", step: 3, type: "make"
  .jumbotron
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")

    %p.lead
      下のフォームを編集して１つ目の自分ルールを作成してください。
      %br
      ex) 夕飯を食べ終わったら１回スクワットをする

    = form_for(:make, url: makes_situation_description_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.text_area :rule1, required: true, maxlength: 255, class: "form-control mt-5 placeholder", value: "#{@norm}",
                            placeholder: "「すでにある習慣を実行したらノルマを行う」という形で自分ルールを作成してください"

      = f.submit "次へ", class: "btn btn-info mt-5"
  %a.hint-text.d-inline-block.mt-3.mb-5{"data-toggle" => "modal", "href" => "#makeHintModal1"}
    ルール作成のヒント

  #makeHintModal1.modal.fade{"tab-index" => "-1", "role" => "dialog", "aria-labelledby" => "makeHintModal1Label", "aria-hidden" => "true"}
    .modal-dialog.modal-dialog-centered{"role" => "document"}
      .modal-content
        .modal-header
          %h5.m-0.modal-titel#makeHintModal1Title ヒント
          %button.close{"type" => "button", "data-dismiss" => "modal", "aria-label" => "閉じる"}
            %span{"aria-hidden" => "true"} &times;
        .modal-body.text-justify
          %p
            &emsp;自分の意志の力で習慣づくりをしようとすると挫折する確率が高くなってしまいます。
          %p
            &emsp;継続するコツは行動を「ルール化」してしまい、自分の意志とは関係なく実行することです。その方法の１つがすでにある習慣と新しくはじめたい行動をセットにするというものです。
          %p
            &emsp;「食事をする」「電車に乗る」「お風呂に入る」などの普段当たり前におこなっている行動にノルマを結びつけることで、気軽に有効なルールを決めることができます。
          %p
            &emsp;ノルマの頻度を調整したい場合は「月・水・金曜日は仕事が終わったらジムにいく」などの条件にしても大丈夫です。この時も必ずすでにある習慣とセットにしてください。

app/views/makes/rule2_input.html.haml
.container.makes-new-wrapper.text-center
  = render "shared/stepbar", step: 5, type: "make"
  .jumbotron
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      下のフォームを編集して２つ目の自分ルールを作成してください。
      %br
      ex) めんどくさいと思ったら太ってる自分の写真を見返す

    = form_for(:make, url: makes_path) do |f|
      = f.hidden_field :title, value: @title
      = f.hidden_field :rule1, value: @rule1
      = f.text_area :rule2, required: true, maxlength: 255, class: "form-control mt-5 placeholder", value: "#{@situation}",
                            placeholder: "「挫折しそうな状況になったら対策を行う」という形で自分ルールを作成してください"

      = f.submit "完成！", class: "btn btn-info mt-5"

  %a.hint-text.d-inline-block.mt-3.mb-5{"data-toggle" => "modal", "href" => "#makeHintModal2"}
    ルール作成のヒント

  #makeHintModal2.modal.fade{"tab-index" => "-1", "role" => "dialog", "aria-labelledby" => "makeHintModal2Label", "aria-hidden" => "true"}
    .modal-dialog.modal-dialog-centered{"role" => "document"}
      .modal-content
        .modal-header
          %h5.m-0.modal-titel#makeHintModal2Title ヒント
          %button.close{"type" => "button", "data-dismiss" => "modal", "aria-label" => "閉じる"}
            %span{"aria-hidden" => "true"} &times;
        .modal-body.text-justify
          %p
            &emsp;「どうしても時間がない」「どうしても疲れて眠い」というような状況では、無理にノルマをやるよりも代わりにやる日を決める方が有効です。
            %br
            ex) 「疲れて眠い場合は、寝てしまって次の日の朝起きたらすぐにノルマをやる。」

app/views/makes/show.html.haml
.container.makes-show-wrapper.text-center
  .jumbotron.mt-5.mx-auto.p-0#make-rule
    %section.title.border-bottom.px-3
      %p.section-title 身につけたい習慣
      %p.content
        = @make.title
    %section.rule1.border-bottom.px-3
      %p.section-title ルール①
      %p.content
        = @make.rule1
    %section.rule2.border-bottom.px-3
      %p.section-title ルール②
      %p.content
        = @make.rule2
    %section.date.border-bottom.px-3
      %p.section-title 作成日
      %p.content
        = @make.created_at.strftime('%Y/%m/%d')
    %section.px-3.d-none#make-progress
      %p.section-title 進捗
      .progressRange
        = form_for(@make, remote: true) do |f|
          = f.range_field :progress, min: 0, max: 100, step: 1, value: @make.progress, onchange: 'Rails.fire(this.form, "submit")'
          %span
            = "#{@make.progress}%"
  .row
    = link_to "画像をダウンロードする", "#", download: "myrule_#{@make.id}", id: "make-download", class: "btn btn-success col-6 offset-3 col-md-4 offset-md-4 mt-4 mb-2"
    = link_to "ルールを削除する", habit_path(@make), method: :delete, class: "btn btn-secondary col-6 offset-3 col-md-4 offset-md-4 my-5", data: { confirm: "このルールを削除しますか？" }

app/views/makes/situation_description.html.haml
.container.makes-new-wrapper
  .jumbotron.mt-5.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      ２つ目の自分ルールを作成していきます。
      %br
      ノルマを実行していく上で、うまくいかないことがあると思います。
      %br
      あらかじめその対策を考えておくことで、習慣づくりの成功率を上げましょう。

    = form_for(:make, url: makes_situation_input_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.hidden_field :rule1, value: @rule1
      = f.submit "次へ", class: "btn btn-info mt-5"

app/views/makes/situation_input.html.haml
.container.makes-new-wrapper
  = render "shared/stepbar", step: 4, type: "make"
  .jumbotron.text-center
    = link_to "javascript:void(0);", onclick: "history.back()", class: "back-icon" do
      = icon("fa", "arrow-left")
    %p.lead
      まず、挫折しそうになる状況や習慣が続かなくなる場面を想像してください。
      %br
      ex) 「疲れて眠い」「めんどくさくなってしまう」など

    = form_for(:make, url: makes_rule2_description_path, method: :get) do |f|
      = f.hidden_field :title, value: @title
      = f.hidden_field :rule1, value: @rule1
      = f.text_field :situation, required: true, maxlength: 150, class: "form-control mt-5 placeholder", placeholder: "挫折しそうになる状況を入力してください"

      = f.submit "次へ", class: "btn btn-info mt-5"