config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "/signup", to: "users#new"
  get "/auth/:provider/callback", to: "users#twitter_login"
  get "/admin/users", to: "users#index"
  patch "/users/:id/profile", to: "users#update_profile", as: "update_profile"
  patch "/users/:id/password", to: "users#update_password", as: "update_password"
  patch "/users/:id/avatar", to: "users#update_avatar", as: "update_avatar" # デモアカウント用
  get "/users/:id/delete", to: "users#delete", as: "delete_page"
  resources :users, except: [:index, :update]

  resources :account_activations, only: [:new, :create, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :habits, only: [:destroy]
  get "/habits/select", to: "habits#select"

  get "/makes/title", to: "makes#title"
  get "/makes/norm_description", to: "makes#norm_description"
  get "/makes/norm_input", to: "makes#norm_input"
  get "/makes/rule1_description", to: "makes#rule1_description"
  get "/makes/rule1_input", to: "makes#rule1_input"
  get "/makes/situation_description", to: "makes#situation_description"
  get "/makes/situation_input", to: "makes#situation_input"
  get "/makes/rule2_description", to: "makes#rule2_description"
  get "/makes/rule2_input", to: "makes#rule2_input"
  resources :makes, only: [:create, :show, :update]

  get "/quits/title", to: "quits#title"
  get "/quits/situation_description", to: "quits#situation_description"
  get "/quits/situation_input", to: "quits#situation_input"
  get "/quits/rule1_description", to: "quits#rule1_description"
  get "/quits/rule1_input", to: "quits#rule1_input"
  get "/quits/rule2_description", to: "quits#rule2_description"
  get "/quits/rule2_input", to: "quits#rule2_input"
  resources :quits, only: [:create, :show, :update]
end

app/models/user.rb
class User < ApplicationRecord
  include Hashid::Rails
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  before_destroy :forbid_destroy_last_admin_user
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { in: 6..50 }, allow_nil: true
  validate :avatar_size

  has_many :habits, dependent: :destroy
  has_many :makes, dependent: :destroy
  has_many :quits, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  # ハッシュ値を返す
  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def self.find_or_create_from_auth_hash(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    name = auth_hash[:info][:name]
    image_url = auth_hash[:info][:image]

    self.find_or_create_by!(provider: provider, uid: uid) do |user|
      user.name = name
      user.email = User.dummy_email(uid, provider)
      user.password = User.new_token
      user.image_url = image_url
      user.activated = true
    end
  end

  def self.dummy_email(uid, provider)
    "#{uid}-#{provider}@dummy.com"
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token)) # rubocop:disable Rails/SkipsModelValidations
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil) # rubocop:disable Rails/SkipsModelValidations
  end

  def activate
    update_attribute(:activated, true) # rubocop:disable Rails/SkipsModelValidations
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def resend_activation_email
    update_attribute(:activated, false) # rubocop:disable Rails/SkipsModelValidations
    create_activation_digest and self.save
    send_activation_email
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now) # rubocop:disable Rails/SkipsModelValidations
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def fail_login
    update!({ failed_attempts: failed_attempts + 1 })
    if failed_attempts >= 5
      update!({
        locked_at: Time.current,
        failed_attempts: 0,
      })
    end
  end

  def locked?
    locked_at && (Time.current < locked_at + 30.minutes)
  end

  private

    def downcase_email
      self.email.downcase!
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

    def forbid_destroy_last_admin_user
      throw(:abort) if self.admin? && User.where(admin: true).count == 1
    end

    def avatar_size
      if avatar.size > 5.megabytes
        errors.add(:avatar, "は5MB以下にしてください")
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController # rubocop:disable Metrics/ClassLength
  before_action :check_login, only: [:index, :show, :edit, :update_profile, :update_password, :delete, :destroy]
  before_action :forbid_login_user, only: [:new, :create]
  before_action :forbid_twitter_login_user, only: [:update_password]
  before_action :check_correct_user, only: [:show, :edit, :update_profile, :update_password, :delete]
  before_action :check_admin, only: [:index]
  before_action :check_destroy, only: [:destroy]
  before_action :forbid_test_user, only: [:update_profile, :update_password, :destroy]

  def index
    @users = User.order(id: :asc).page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      log_in @user
      flash[:success] = "ユーザー登録しました"
      redirect_to @user
    else
      render :new
    end
  end

  def twitter_login
    user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
    if user
      log_in user
      flash[:success] = "ログインしました"
      redirect_back_or user
    else
      flash[:warning] = "ログインに失敗しました"
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update_profile
    @user = User.find(params[:id])
    before_change_email = @user.email
    if @user.update(user_params)
      @user.resend_activation_email unless @user.email == before_change_email
      flash[:success] = "プロフィールを更新しました"
      redirect_to @user
    else
      render :edit
    end
  end

  def update_password
    @user = User.find(params[:id])
    unless @user.authenticate(params[:user][:current_password])
      @user.errors.add(:base, "現在のパスワードが違います")
      render :edit and return
    end
    if params[:user][:password].blank?
      @user.errors.add(:password, :blank)
      render :edit and return
    end
    if @user.update(user_params)
      flash[:success] = "パスワードを更新しました"
      redirect_to @user
    else
      render :edit
    end
  end

  # デモアカウント用
  def update_avatar
    @user = User.find(params[:id])
    if @user.update(params.require(:user).permit(:avatar))
      flash[:success] = "プロフィール画像を更新しました"
      redirect_to edit_user_path(@user)
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    user = User.find(params[:id])
    redirect_back(fallback_location: root_url) and return if user.admin?
    user.destroy!
    if current_user.admin?
      redirect_to admin_users_path
    else
      flash[:success] = "アカウントを削除しました"
      redirect_to root_url
    end
  end

  private

    def user_params
      params.
        require(:user).
        permit(:name,
               :email,
               :avatar,
               :password,
               :password_confirmation)
    end

    def forbid_twitter_login_user
      redirect_to(current_user) if current_user.provider == "twitter"
    end

    def check_correct_user
      @user = User.find(params[:id])
      redirect_to(current_user) unless @user == current_user
    end

    def check_admin
      redirect_to(current_user) unless current_user.admin?
    end

    def check_destroy
      @user = User.find(params[:id])
      redirect_to(current_user) unless current_user.admin? || @user == current_user
    end

    # デモアカウント用
    def forbid_test_user
      user = User.find(params[:id])
      if user.email == "test_user@example.com"
        redirect_to edit_user_path(user)
        flash[:warning] = "デモ用アカウントはプロフィール画像のみ編集できます"
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.haml
%ul.nav.nav-tabs.nav-justified.text-center
  %li.active.col-6
    .show.active.select-edit-tab.pb-2{ "data-target" => "#profile-edit", "data-toggle" => "tab"} プロフィール
  %li.col-6
    .select-edit-tab.pb-2{ "data-target" => "#password-edit", "data-toggle" => "tab"} パスワード
.tab-content.tabs-profile-edit.col-12
  #profile-edit.tab-pane.fade.active.show.in
    = image_tag "", class: "d-none", id: "avatar-img-prev"
    = image_tag current_user.avatar.url, class: "avatar-present-img"
    = form_for(user, url: update_profile_path(params[:id])) do |f|
      .text-center
        = f.label :avatar, "プロフィール画像を選択", class: "file-upload-label"
      = f.file_field :avatar, accept: "image/jpeg,image/gif,image/png", class: "d-none"

      = render "shared/error_messages", object: f.object

      = f.label :name, class: "form-label mt-4"
      = f.text_field :name, required: true, maxlength: 50, class: "form-control placeholder mb-3", placeholder: "ユーザー名"

      = f.label :email, class: "form-label"
      = f.email_field :email, required: true, maxlength: 255, class: "form-control placeholder mb-4", placeholder: "メールアドレス"

      = f.submit "プロフィールを更新する", class: "btn btn-info btn-block btn-update mt-4"
  #password-edit.tab-pane.fade.col-12
    = form_for(user, url: update_password_path(params[:id]), html: {id: "user_edit_2"}) do |f|
      = render "shared/error_messages", object: f.object
      = f.password_field :current_password, required: true, class: "form-control placeholder mt-5 mb-4", placeholder: "現在のパスワード"

      = f.password_field :password, required: true, maxlength: 50, class: "form-control placeholder mb-4", placeholder: "新しいパスワード（６文字以上）"

      = f.password_field :password_confirmation, required: true, maxlength: 50, class: "form-control placeholder", placeholder: "新しいパスワード（確認）"

      = f.submit "パスワードを更新する", class: "btn btn-info btn-block btn-update mt-4"

app/views/users/_edit_form_for_test_user.html.haml
%p.mb-4
  デモ用アカウントではプロフィール画像のみ編集できます
%ul.nav.nav-tabs.nav-justified.text-center
  %li.active.col-6
    .show.active.select-edit-tab.pb-2{ "data-target" => "#profile-edit", "data-toggle" => "tab"} プロフィール
  %li.col-6
    .select-edit-tab.pb-2{ "data-target" => "#password-edit", "data-toggle" => "tab"} パスワード
.tab-content.tabs-profile-edit.col-12
  #profile-edit.tab-pane.fade.active.show.in
    = image_tag "", class: "d-none", id: "avatar-img-prev"
    = image_tag current_user.avatar.url, class: "avatar-present-img"
    = form_for(user, url: update_avatar_path(params[:id])) do |f|
      .text-center
        = f.label :avatar, "プロフィール画像を選択", class: "file-upload-label"
      = f.file_field :avatar, accept: "image/jpeg,image/gif,image/png", class: "d-none"

      = render "shared/error_messages", object: f.object

      = f.label :name, class: "form-label mt-4"
      = f.text_field :name, required: true, maxlength: 50, class: "form-control placeholder mb-3",
                            placeholder: "ユーザー名", readonly: true

      = f.label :email, class: "form-label"
      = f.email_field :email, required: true, maxlength: 255, class: "form-control placeholder mb-4",
                              placeholder: "メールアドレス", readonly: true

      = f.submit "プロフィール画像を更新する", class: "btn btn-info btn-block btn-update mt-4"
  #password-edit.tab-pane.fade.col-12
    = form_for(user, url: update_password_path(params[:id]), html: {id: "user_edit_2"}) do |f|
      = render "shared/error_messages", object: f.object
      = f.password_field :current_password, required: true, class: "form-control placeholder mt-5 mb-4",
                                            placeholder: "現在のパスワード", readonly: true

      = f.password_field :password, required: true, maxlength: 50, class: "form-control placeholder mb-4",
                                    placeholder: "新しいパスワード（６文字以上）", readonly: true

      = f.password_field :password_confirmation, required: true, maxlength: 50, class: "form-control placeholder",
                                                 placeholder: "新しいパスワード（確認）", readonly: true

      = f.submit "パスワードを更新する", class: "btn btn-info btn-block btn-update mt-4", disabled: true

app/views/users/_edit_form_for_twitter.html.haml
%p.text-center.mb-0
  プロフィール編集
%img#avatar-img-prev.d-none{src: "#"}
- if current_user.avatar?
  = image_tag current_user.avatar.url, class: "avatar-present-img"
- else
  -# Twitterのプロフィール画像を原寸大で取得するための処理
  = image_tag current_user.image_url.gsub(/_normal/, ""), class: "avatar-present-img"
= form_for(user, url: update_profile_path(params[:id])) do |f|
  .text-center
    = f.label :avatar, "プロフィール画像を選択", class: "file-upload-label"
  = f.file_field :avatar, accept: "image/jpeg,image/gif,image/png", class: "d-none"

  = render "shared/error_messages", object: f.object

  = f.label :name, "ユーザー名", class: "form-label mt-4"
  = f.text_field :name, required: true, maxlength: 50, class: "form-control placeholder mb-4", placeholder: "新しいユーザー名", value: current_user.name
  
  = hidden_field_tag :email, user.email

  = f.submit "プロフィールを更新する", class: "btn btn-info btn-block btn-update mt-4"

app/views/users/delete.html.haml
.container.user-delete-wrapper
  .card.card-container
    .jumbotron
      %ul
        %li.mb-4
          アカウントを削除すると、これまでに作成されたデータは全て削除されます。
        %li
          削除されたデータを復旧することはできません。
    - if @user.email == "test_user@example.com" # デモアカウント用
      %button.btn.btn-danger{href: "#", disabled: true} アカウントを削除する
      %span.mt-2
        デモアカウントは削除できません
    - else
      = link_to "アカウントを削除する", user_path(@user), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger"

app/views/users/edit.html.haml
.container.user-edit-wrapper
  .card.card-container
    - if @user.provider == "twitter"
      = render "edit_form_for_twitter", user: @user
    - elsif @user.email == "test_user@example.com" # デモアカウント用
      = render "edit_form_for_test_user", user: @user
    - else
      = render "edit_form", user: @user
  = link_to "アカウントを削除する場合はこちらから", delete_page_path(@user), class: "invite-text invite-delete text-center mb-5"

app/views/users/index.html.haml
.user-index-wrapper
  %h1.text-center.my-5 ユーザー一覧
  %table.table.table-bordered.table-striped
    %thead
      %th.user-id<
        = User.human_attribute_name :id
      %th.user-name<
        = User.human_attribute_name :name
      %th.user-email<
        = User.human_attribute_name :email
      %th.user-delete<
    - @users.each do |user|
      %tr
        %td.user-id<
          = user.id
        %td.user-name<
          = user.name
        %td.user-email<
          = user.email
        %td.user-delete<
          - unless user.admin?
            = link_to "削除", user_path(user), method: :delete, data: { confirm: "本当に削除しますか？" }
  = paginate @users

app/views/users/new.html.haml
.container
  .card.card-container
    %p
      テストユーザーとしてログインできます
    = form_for(:session, url: login_path) do |f|
      = f.hidden_field :email, value: "test_user@example.com"
      = f.hidden_field :password, value: "test1234"
      = f.submit "お試しログイン", class: "btn btn-info btn-block demo-btn mt-3 mb-2 mx-auto"
  .card.card-container
    = image_tag "logo.png", size: "200x55", class: "mx-auto"
    = link_to  '/auth/twitter', class: "btn btn-twitter mt-4", id: "twitter-signup" do
      = icon("fab", "twitter", class: "mr-1")
      %span Twitterで登録
    .divide-text-signup またはメールアドレスで登録
    = form_for(@user) do |f|
      = render "shared/error_messages", object: f.object
      = f.text_field :name, required: true, maxlength: 50, class: "form-control placeholder mt-4 mb-4", placeholder: "ユーザー名"

      = f.email_field :email, required: true, maxlength: 255, class: "form-control placeholder mb-4", placeholder: "メールアドレス"

      = f.password_field :password, required: true, maxlength: 50, class: "form-control placeholder mb-4", placeholder: "パスワード（６文字以上）"

      = f.password_field :password_confirmation, required: true, maxlength: 50, class: "form-control placeholder", placeholder: "パスワード（確認）"

      = f.submit "新規登録", class: "btn btn-primary btn-block btn-signup mt-4"
      = link_to "すでにアカウントをお持ちの場合", login_path, class: "invite-text"

app/views/users/show.html.haml
.container.user-show-wrapper
  %h1.text-center.my-5
    = "自分ルール一覧"
  %ul.nav.nav-tabs.d-flex.justify-content-between
    %li.nav-item
      %a.nav-link.active{"href" => "#tab1", "data-toggle" => "tab"} すべて
    %li.nav-item
      %a.nav-link.nav-make{"href" => "#tab2", "data-toggle" => "tab"} 身につけたい習慣
    %li.nav-item
      %a.nav-link.nav-quit{"href" => "#tab3", "data-toggle" => "tab"} やめたい習慣
  .jumbotron.mt-5.mx-auto.p-0
    .tab-content
      #tab1.tab-pane.active
        - if @user.habits.empty?
          %p.rule-empty-text
            まだ自分ルールがありません
            %br
            ルール作成は
            = link_to "こちら", habits_select_path
            から
        - else
          - @user.habits.order(created_at: :desc).each do |habit|
            .habit.d-flex.justify-content-around.align-items-center.border-bottom{ class: "#{habit.type == 'Make' ? 'make' : 'quit'}" }
              = link_to "", habit.type == "Make" ? make_path(habit.hashid) : quit_path(habit.hashid)
              %span.title
                = habit.title
              %span.number
                = "#{habit.progress}%"
      #tab2.tab-pane
        - if @user.makes.empty?
          %p.rule-empty-text
            まだ自分ルールがありません
            %br
            ルール作成は
            = link_to "こちら", makes_title_path
            から
        - else
          - @user.makes.order(created_at: :desc).each do|make|
            .habit.make.d-flex.justify-content-around.align-items-center.border-bottom
              = link_to "", make
              %span.title
                = make.title
              %span.number
                = "#{make.progress}%"
      #tab3.tab-pane
        - if @user.quits.empty?
          %p.rule-empty-text
            まだ自分ルールがありません
            %br
            ルール作成は
            = link_to "こちら", quits_title_path
            から
        - else
          - @user.quits.order(created_at: :desc).each do|quit|
            .habit.quit.d-flex.justify-content-around.align-items-center.border-bottom
              = link_to "", quit
              %span.title
                = quit.title
              %span.number
                = "#{quit.progress}%"
  = link_to habits_select_path , class: "fixed-rule-make-btn" do
    %div 作成
    %i.fas.fa-plus