config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "/signup", to: "users#new"
  get "/auth/:provider/callback", to: "users#twitter_login"
  get "/admin/users", to: "users#index"
  patch "/users/:id/profile", to: "users#update_profile", as: "update_profile"
  patch "/users/:id/password", to: "users#update_password", as: "update_password"
  patch "/users/:id/avatar", to: "users#update_avatar", as: "update_avatar" # デモアカウント用
  get "/users/:id/delete", to: "users#delete", as: "delete_page"
  resources :users, except: [:index, :update]

  resources :account_activations, only: [:new, :create, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :habits, only: [:destroy]
  get "/habits/select", to: "habits#select"

  get "/makes/title", to: "makes#title"
  get "/makes/norm_description", to: "makes#norm_description"
  get "/makes/norm_input", to: "makes#norm_input"
  get "/makes/rule1_description", to: "makes#rule1_description"
  get "/makes/rule1_input", to: "makes#rule1_input"
  get "/makes/situation_description", to: "makes#situation_description"
  get "/makes/situation_input", to: "makes#situation_input"
  get "/makes/rule2_description", to: "makes#rule2_description"
  get "/makes/rule2_input", to: "makes#rule2_input"
  resources :makes, only: [:create, :show, :update]

  get "/quits/title", to: "quits#title"
  get "/quits/situation_description", to: "quits#situation_description"
  get "/quits/situation_input", to: "quits#situation_input"
  get "/quits/rule1_description", to: "quits#rule1_description"
  get "/quits/rule1_input", to: "quits#rule1_input"
  get "/quits/rule2_description", to: "quits#rule2_description"
  get "/quits/rule2_input", to: "quits#rule2_input"
  resources :quits, only: [:create, :show, :update]
end

app/views/layouts/_footer.html.haml
%footer
  %h5.m-0 &copy; MakeHabits

app/views/layouts/_header.html.haml
%header
  %nav.navbar.navbar-expand-md.navbar-light.bg-light.sticky-top
    .container-fluid
      %a.navbar-brand{href: "#{logged_in? ? user_path(current_user) : '/'}"}
        = image_tag "logo.png", size: "170x50"
      %button.navbar-toggler{type: "button", "data-toggle" => "collapse", "data-target" => "#navbarResponsive"}
        %span.navbar-toggler-icon
      .collapse.navbar-collapse#navbarResponsive
        %ul.navbar-nav.ml-auto
          - if logged_in?
            %li.nav-item
              = link_to "自分ルール作成", habits_select_path, class: "nav-link"
            %li.nav-item
              = link_to "自分ルール一覧", current_user, class: "nav-link"
            %li.nav-item.dropdown
              %a.nav-link.dropdown-toggle#navbarDropdown{"href" => "#", "data-toggle" => "dropdown", "role" => "button", "aria-haspopup" => "true", "aria-expanded" => "false"}
                - if current_user.provider == "twitter"
                  - if current_user.avatar?
                    = image_tag current_user.avatar.url, class: "header-avatar"
                  - else
                    = image_tag current_user.image_url, class: "header-avatar"
                - else
                  = image_tag current_user.avatar.url, class: "header-avatar"
                %span.user-name
                  = current_user.name
              .dropdown-menu.dropdown-menu-right{"aria-haspopup" => "true"}
                - if current_user.admin?
                  = link_to "管理ページ", admin_users_path, class: "dropdown-item"
                = link_to "プロフィール編集", edit_user_path(current_user), class: "dropdown-item"
                = link_to "ログアウト", logout_path, method: "delete", class: "dropdown-item"
          - else
            %li.nav-item
              = link_to "新規登録", signup_path, class: "nav-link"
            %li.nav-item
              = link_to "ログイン", login_path, class: "nav-link"

app/views/layouts/application.html.haml
!!!
%html{lang: "ja"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %title MakeHabits
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'https://fonts.googleapis.com/css?family=M+PLUS+1p'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    - flash.each do |msg_type, msg|
      = content_tag(:div, msg, class: "alert alert-#{msg_type} text-center text-break")
    .page-wrapper
      = yield
    = render 'layouts/footer'